### ISSUE TITLE
corpus explorer unavailable?

### ISSUE THREAD

**Issue by michaelcapizzi** [bhoov/exbert#1]
Awesome tool!  Can't wait to dig into it more.

The options for selecting corpus search on the demo page aren't available to click on (when I do so, I get a red circle with a slash through it).  I'm using chrome.

Am I missing something?

**Comment by bhoov** [comment]
You will need to click on a token in order for the tool to know which token you care to search for. The buttons require one token and at least one head to be selected to be activated.
