### ISSUE TITLE
Environment not able to recognize `from_pretrained` from `transformer_details`

### ISSUE THREAD

**Issue by wrosko** [bhoov/exbert#14]
Today I was trying to generate embeddings with the `create_corpus.py` script and the respective hdf5/faiss scripts. Initially things were working but in an attempt to try and figure out how to increase the max input length of text, I ended up re-pulling the repo.

What ensued, and after multiple varying attempts to create brand new environments, was this error regarding `from_pretrained` and `transformer_details` from the ` hdf5 script. There may also be an issue with the faiss script too, but I haven't tried it. 
![image](https://user-images.githubusercontent.com/7385473/88212293-04867b80-cc25-11ea-893a-4a6fa6849bee.png)

Any idea what's causing this? Could it be a dependency issue from one of the packages that didn't have a specified version  indicated? I've attached the environment package information below
[exbert_dependencies.txt](https://github.com/bhoov/exbert/files/4961702/exbert_dependencies.txt)

**Comment by bhoov** [comment]
Good catch! Not a dependency problem, but an incorrect import.

**Comment by wrosko** [comment]
Wonderful! I was just digging around the code this morning and stumbled across the name change right before you made the correction. Thanks!

If I should open a new issue let me know, but how do I go about changing the spacy max text length?

**Comment by bhoov** [comment]
Yes, please open a new issue it will help to keep that topic separate for others who may want to do something similar :)
