### ISSUE TITLE
loading weights with default model

### ISSUE THREAD

**Issue by prajjwal1** [bhoov/exbert#18]
Hi, thanks for your project.

I had a simple question, I didn't find answer to this query in the `README`. I want to use `bert-base-uncased` and `bert-large-uncased` with my weights (trained on a GLUE task) and want to visualize what you showed in demo on RHS (which token the model chooses to pay attention to). Could you please provide the recommended steps ?

**Comment by bhoov** [comment]
Custom weights require you to run exBERT locally. The steps would then be as follows:

1. Create your annotated corpus. Find a small-medium sized .txt file (we demo with the Wizard of Oz from Gutenberg.org) and pass it through the `create_corpus.py` script, with full instructions given in the data processing [README](https://github.com/bhoov/exbert/tree/master/server/data_processing).

2. Run your model locally as described in the main [README](https://github.com/bhoov/exbert#running-locally)

**Comment by prajjwal1** [comment]
Thanks a lot.
