### ISSUE TITLE
Corpus View 500 error on Live Demo

### ISSUE THREAD

**Issue by usuyama** [bhoov/exbert#19]
Wanted to try Corpus View on the live demo page https://exbert.net/
but when I click the buttons

![image](https://user-images.githubusercontent.com/344133/98455981-f8660000-21ba-11eb-9592-b826d1ed07ce.png)

it seems to be getting `POST https://exbert.net/api/k-nearest-embeddings 500 (Internal Server Error)`

![image](https://user-images.githubusercontent.com/344133/98455929-39114980-21ba-11eb-8e4f-59a5362f05d3.png)

**Comment by bhoov** [comment]
Great catch thank you. It seems that about 4 months ago I introduced a bug that went unnoticed in the live server until the server had to restart.

The issue has been fixed in dcbfc6e159c5bb419c9b913d126821dd56b98abf

**Comment by usuyama** [comment]
Thank you!
